apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component-techdocs-v2.0

  devxstate: Approved
  avgRating: 4.4
  
  comments:
    - reviewer:
        user: micahel
        date: "08/01/2021"
        comments:
          Component looks good, but few suggestions, please consider them. Add
          proper comments, Add benchmarks , provide proper comments
    - publisher:
        user: siva.kumar2
        date: "08/05/2021"
        comments:
          Thanks for your valuable feedback, i will work on it and get back to
          you
    - publisher:
        user: siva.kumar2
        date: "08/05/2021"
        comments: I worked on the feedback, please review it again
    - reviewer:
        user: micahel
        date: "08/06/2021"
        comments: Looks great, approved.
  description: Full blown sample yaml file that describes about the component
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/chennas/gwc139
    
  tags:
    - Angular
    - javascript
  links:
    - url: https://example.com/user
      title: Examples Users
      description: description for Examples Users
    - url: https://example.com/group
      title: Example Group
      description: description for Example Group 
spec:
  type: service
  lifecycle: production
  owner: user:prasun.mukherjee
  subcomponentOf: artist-lookup
  providesApis:
    - spotify
  consumesApis:
    - starwars-graphql
  dependsOn:
    - component:CBRE-1-order
    - resource:artists-db
